### ISSUE TITLE
Full Disk Access issue

### ISSUE THREAD

**Issue by yasingunaydiin** [fjxmlzn/FindMyHistory#23]
I've granted it access in the Security settings and I've tried to add 'sudo' in the commandline but I cant get it to work.

`sudo git clone https://github.com/fjxmlzn/FindMyHistory.git
cd FindMyHistory
pip3 install -r requirements.txt
python3 main.py
Password:
fatal: destination path 'FindMyHistory' already exists and is not an empty directory.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tabulate[widechars] in /Users/yasingunaydin/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 1)) (0.9.0)
Requirement already satisfied: wcwidth in /Users/yasingunaydin/Library/Python/3.9/lib/python/site-packages (from tabulate[widechars]->-r requirements.txt (line 1)) (0.2.13)
WARNING: You are using pip version 21.2.4; however, version 24.0 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/Users/yasingunaydin/FindMyHistory/main.py", line 125, in <module>
    curses.wrapper(partial(main, args=args))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/yasingunaydin/FindMyHistory/main.py", line 91, in main
    log_manager.refresh_log()
  File "/Users/yasingunaydin/FindMyHistory/lib/log_manager.py", line 83, in refresh_log
    items_dict = self._get_items_dict()
  File "/Users/yasingunaydin/FindMyHistory/lib/log_manager.py", line 60, in _get_items_dict
    raise RuntimeError(f'No devices found. Please check if Full Disk '
RuntimeError: No devices found. Please check if Full Disk Access has been granted to Terminal.
yasingunaydin@Air-van-Yasin FindMyHistory % `

**Comment by arielleko1** [comment]
same problem here!:(

**Comment by kamikaziH2Omln** [comment]
This sounds like Terminal does not have Full Write Access (it doesn't get it by default).

https://www.alfredapp.com/help/troubleshooting/indexing/terminal-full-disk-access/

Make sure to grant it this access via the "Privacy" tab in System Preferences. @yasingunaydiin @arielleko1

**Comment by yasingunaydiin** [comment]
> This sounds like Terminal does not have Full Write Access (it doesn't get it by default).
> 
> https://www.alfredapp.com/help/troubleshooting/indexing/terminal-full-disk-access/
> 
> Make sure to grant it this access via the "Privacy" tab in System Preferences. @yasingunaydiin @arielleko1

I have granted it access like i said. Turned it off and on 3 times.

**Comment by duganj** [comment]
I'm having a similar issue as well, and I'm wondering if its associated with a recent MacOS update. I had the script working this morning on Sonoma 14.3.1 (M1 MacMini). I then upgraded to 14.4.1 and now I'm getting errors that suggest checking Full Write Access (which I've had enabled since when everything was working).

```
johndugan@Johns-Mac-mini-2 FindMyHistory % python3 main.py                                  
Traceback (most recent call last):
  File "/Users/johndugan/FindMyHistory/main.py", line 125, in <module>
    curses.wrapper(partial(main, args=args))
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/johndugan/FindMyHistory/main.py", line 91, in main
    log_manager.refresh_log()
  File "/Users/johndugan/FindMyHistory/lib/log_manager.py", line 83, in refresh_log
    items_dict = self._get_items_dict()
  File "/Users/johndugan/FindMyHistory/lib/log_manager.py", line 60, in _get_items_dict
    raise RuntimeError(f'No devices found. Please check if Full Disk '
RuntimeError: No devices found. Please check if Full Disk Access has been granted to Terminal.
```

**Comment by duganj** [comment]
See comments here, looks like Apple may have encrypted those .data files with the recent update. https://gist.github.com/henrik242/1da3a252ca66fb7d17bca5509a67937f

**Comment by wkddudwo** [comment]
저같은 단순 실수로 오류가 뜨는 분들을 위해 작성합니다 :

1.osx 에 애플 아이디로 로그인 되어 있어야 합니다.
2.FindMy 앱을 한번이라도 실행해 보아야 합니다.
3.duganj 님의 말씀처럼 FindMy 를 한번이라도 실행했다면 `$HOME/Library/Caches/com.apple.findmy.fmipcore/` 경로에 ~~.data 파일이 있어야합니다.
4.Full Access permission 이 허용되어 있어야 합니다.(README 본문처럼 Terminal 권한이 허용되어있어야함.)
5.duganj 님의 말씀처럼 .data가 암호화 되어있는 sonoma 이상의 버전에서는 실행할 수 없습니다.
![스크린샷 2024-06-12 180224](https://github.com/fjxmlzn/FindMyHistory/assets/115683471/367c711f-a347-4313-8c0f-07f4a3caefe8)

내 국가에서는 위치추적이 지원되지 않아서 NULL 로 뜨는 것 같습니다.

**Comment by wkddudwo** [comment]
> I am writing this for people like me who get errors due to simple mistakes:
> 
> 1. You must be logged in to osx with your Apple ID.
> 2. You must run the FindMy app at least once.
> 3. As Duganj said, if you have run FindMy even once, there should be a ~~.data file in the `$HOME/Library/Caches/com.apple.findmy.fmipcore/` path.
>    4.Full Access permission must be granted. (Terminal permission must be granted as in the README text.)
> 4. As Duganj said, it cannot be run on sonoma or later versions where .data is encrypted.
> 
> Location tracking is not supported in my country, so it appears to be NULL.

![스크린샷 2024-06-12 180224](https://github.com/fjxmlzn/FindMyHistory/assets/115683471/e50cfb0d-3b9c-4e57-8dc5-e4a199867aff)

**Comment by bjrne** [comment]
> it cannot be run on sonoma or later versions where .data is encrypted.

This should be in the README at the top! Or at least with a note in "supported devices". I got it to work now on an older Macbook. However, to me it is very misleading to not state that you're incompatible with the current version of Mac OS...
